models.py
from app import db


class Question(db.Model):
    __tablename__ = 'question'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(255), nullable=False)

    options = db.relationship('Option', backref='question')

    def __init__(self, text):
        self.text = text

        
class Option(db.Model):
    __tablename__ = 'option'

    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(255), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'))
    answers = db.relationship('Answer', backref='option')

    def __init__(self, text):
        self.text = text

class Answer(db.Model):
    __tablename__ = 'answer'

    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.String(255), nullable=False)
    option_id = db.Column(db.Integer, db.ForeignKey('option.id'))

    def __init__(self, user, option):
        self.user = user
        self.option_id = option

app.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:postgres@quiz-db-1:5432/postgres'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

app.secret_key = "1212"

db.init_app(app)

with app.app_context():
    db.create_all()

migrate = Migrate(app, db)

from controllers.main_controller import main_controller

app.register_blueprint(main_controller)


if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(debug=True, host="0.0.0.0", port=port)

controllers/main_controller.py
from flask import Blueprint, render_template, abort, request, redirect, url_for
from models import Question, Option, Answer
from app import db

main_controller = Blueprint('main_controller', __name__)

@main_controller.route('/')
def index():
    questions = Question.query.all()
    return render_template('index.html', questions=questions)

@main_controller.route('/create', methods = ['GET', 'POST'])
def products():
    if request.method == 'POST':
        question_text = request.form['question_text']
        options = request.form.getlist('options[]')

        # Create a new question
        question = Question(text=question_text)
        for option_text in options:
            option = Option(text=option_text)
            question.options.append(option)

        # Save to the database
        db.session.add(question)
        db.session.commit()

        return redirect(url_for('main_controller.index'))

    return render_template('create.html')


@main_controller.route('/question/<int:question_id>')
def question(question_id):
    question = Question.query.filter_by(id=question_id).first()
        
    if question:
        return render_template('question.html', question=question)
    else:
       abort(404)


@main_controller.route('/results/<int:question_id>')
def result(question_id):
    question = Question.query.filter_by(id=question_id).first()
        
    if question:
        return render_template('results.html', question=question)
    else:
       abort(404)


@main_controller.route('/submit', methods = ['GET', 'POST'])
def submit_option():
    option_id = request.form.get('response')
    if not option_id:
        return redirect(url_for('main_controller.index'))

    option = Option.query.get(option_id)
    if not option:
        return redirect(url_for('main_controller.index'))

    user = request.form.get('user')
    response = Answer(user=user, option=option_id)

    db.session.add(response)
    db.session.commit()

    return redirect(url_for('main_controller.index'))

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новый вопрос</title>
</head>
<body>

<h2>Новый вопрос</h2>

<form action="/create" method="post">

    <label for="question_text">Текст вопроса:</label><br>
    <textarea id="question_text" name="question_text" rows="4" cols="50" required></textarea><br><br>

    <label for="option1">Ответ 1:</label>
    <input type="text" id="option1" name="options[]" required><br>

    <label for="option2">Ответ 2:</label>
    <input type="text" id="option2" name="options[]" required><br>

    <label for="option3">Ответ 3:</label>
    <input type="text" id="option3" name="options[]"><br>

    <label for="option4">Ответ 4:</label>
    <input type="text" id="option4" name="options[]"><br><br>

    <input type="submit" value="Создать">
</form>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список вопросов</title>
</head>
<body>

<h2>Список вопросов</h2>

<ul>
    {% for question in questions %}
        <li>
            <a href="{{ url_for('main_controller.question', question_id=question.id) }}">{{ question.text }}</a>
            <a href="{{ url_for('main_controller.result', question_id=question.id) }}">Результаты</a>
        </li>
    {% endfor %}
</ul>

</body>
</html>

templates/question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вопрос</title>
</head>
<body>

<h2>{{ question.text }}</h2>

<form action="/submit" method="post">
    <input type="text" name="user"><br><br>
    {% for option in question.options %}
        <input type="radio" id="option{{ option.id }}" name="response" value="{{ option.id }}">
        <label for="option{{ option.id }}">{{ option.text }}</label><br>
    {% endfor %}

    <input type="submit" value="Отправить ответ">
</form>

</body>
</html>

templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Результаты</title>
</head>
<body>

<h2>Ответы на вопрос</h2>

<h3>{{ question.text }}</h3>

<ul>
    {% for option in question.options %}
        <li>{{ option.text }}: {{ option.answers|length }} ответов</li>
    {% endfor %}
</ul>

<p><a href="{{ url_for('main_controller.index') }}">Back to Index</a></p>

</body>
</html>